on:
  push:
    branch: ["master"]

env:
  DOCKER_IMAGE_NAME: k8s-reactjs-dev09

# build docker image, push to dockerhub
jobs:
  ci-job:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Using Commit SHA 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      
      - name: SHow the SHA value 
        run : |
          echo "TAG = ${{env.TAG}}"

      - name: Loigin to dockerhub
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin

      - name: Build and Tag 
        run: |
          docker build -t ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{env.TAG}} .

      - name: Push to Dockerhub 
        run: |
          docker push ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{env.TAG}}

      - name: Logout from Dockerhub
        run : |
          docker logout


# update hrlm repo with new image