on:
  push:
    branch: ["master"]

env:
  DOCKER_IMAGE_NAME: k8s-reactjs-dev09
  HELM_REPO : socheatha/reactjs-plants-chart.git

# build docker image, push to dockerhub
jobs:
  ci-job:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Using Commit SHA 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      
      - name: SHow the SHA value 
        run : |
          echo "TAG = ${{env.TAG}}"

      - name: Loigin to dockerhub
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin

      - name: Build and Tag 
        run: |
          docker build -t ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} .

      - name: Push to Dockerhub 
        run: |
          docker push ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}

      - name: Logout from Dockerhub
        run : |
          docker logout


# update hrlm repo with new image
  cd-job:
    needs: ci-job 
    runs-on: ubuntu-latest
    environment: HELM_ENV
    steps: 
      - name: Installing yq for easily work with the values file 
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Using Commit SHA 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Clone argocd repo 
        run: |
          git clone https://github.com/${{ env.HELM_REPO }} helm_repo 

      - name: Update Helm Chart 
        run: | 
          cd helm_repo/dir_name

          echo "Upate repositoty part of value file"
          yq -i ".image.repository=\"${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}\"" values.yaml

          echo "Update image tag"
          yq -i ".image.tag=\"${{ env.TAG }}\"" values.yaml

          git config --global user.email "username@example.com"
          git config --global user.name "dummyname"
          git add .
          git commit -m "Update helm to use image ${{ env.TAG }}"
          git push https://${{ secrets.GIT_TOKEN }}@github.com/${{ env.HELM_REPO }}

      - name: Clean up 
        run: |
          rm -rf helm_repo